name: mntts
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2022.4.26=h06a4308_0
  - certifi=2022.6.15=py37h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.3=h5eee18b_3
  - openssl=1.1.1p=h5eee18b_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.13=h12debd9_0
  - readline=8.1.2=h7f8727e_1
  - setuptools=61.2.0=py37h06a4308_0
  - sqlite=3.38.5=hc218d9a_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - zlib=1.2.12=h7f8727e_2
  - pip:
    - absl-py==0.15.0
    - appdirs==1.4.4
    - astunparse==1.6.3
    - audioread==2.1.9
    - cached-property==1.5.2
    - cachetools==4.2.4
    - cffi==1.15.1
    - charset-normalizer==2.1.0
    - clang==5.0
    - click==8.1.3
    - cycler==0.11.0
    - cython==0.29.30
    - dataclasses==0.6
    - decorator==5.1.1
    - distance==0.1.3
    - filelock==3.7.1
    - flatbuffers==1.12
    - fonttools==4.34.4
    - g2p-en==2.1.0
    - g2pm==0.1.2.5
    - gast==0.3.3
    - google-auth==1.35.0
    - google-auth-oauthlib==0.4.6
    - google-pasta==0.2.0
    - grpcio==1.32.0
    - h5py==2.10.0
    - huggingface-hub==0.0.8
    - idna==3.3
    - importlib-metadata==4.12.0
    - inflect==5.6.0
    - jamo==0.4.1
    - joblib==1.1.0
    - keras==2.9.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.4.3
    - librosa==0.9.2
    - llvmlite==0.31.0
    - markdown==3.3.7
    - matplotlib==3.5.2
    - nltk==3.7
    - numba==0.48.0
    - numpy==1.18.5
    - oauthlib==3.2.0
    - opt-einsum==3.3.0
    - packaging==21.3
    - pillow==9.2.0
    - pooch==1.6.0
    - protobuf==3.19.4
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.21
    - pyparsing==3.0.9
    - pypinyin==0.46.0
    - python-dateutil==2.8.2
    - pyworld==0.3.0
    - pyyaml==6.0
    - regex==2022.7.9
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - resampy==0.3.1
    - rsa==4.8
    - scikit-learn==1.0.2
    - scipy==1.4.1
    - six==1.15.0
    - soundfile==0.10.3.post1
    - tensorboard==2.3.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - tensorflow-addons==0.11.2
    - tensorflow-estimator==2.3.0
    - tensorflow-gpu==2.3.0
    - tensorflowtts==1.8
    - termcolor==1.1.0
    - textgrid==1.5
    - threadpoolctl==3.1.0
    - tqdm==4.64.0
    - typeguard==2.13.3
    - typing-extensions==3.7.4.3
    - unidecode==1.3.4
    - urllib3==1.26.10
    - werkzeug==2.1.2
    - wrapt==1.12.1
    - zipp==3.8.0
prefix: /home/anaconda3/envs/mntts
